version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/app              
      - /app/node_modules            
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
      - ./config/config.json:/app/config.json
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
