name: Build and Release Deb Package

on:
  push:
    tags:
      - '*'  # Trigger quando viene fatto il push di un tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential devscripts debhelper

      - name: Install Docker
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo usermod -aG docker $USER 

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=1.29.2
          curl -L https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up package structure
        run: |
          mkdir -p debian/source
          echo "3.0 (native)" > debian/source/format
          echo "9" > debian/compat

      - name: Create control file
        run: |
          cat << EOF > debian/control
          Source: bdcas
          Section: devel
          Priority: optional
          Maintainer: Dksengine <info@dksengine.it>
          Build-Depends: debhelper (>= 9)
          Standards-Version: 4.5.0

          Package: bdcas
          Architecture: any
          Depends: \${shlibs:Depends}, \${misc:Depends}, docker-ce, docker-compose
          Description: Blue Dolphin Computer Aquarium System Debian
          EOF

      - name: Create rules file
        run: |
          cat << EOF > debian/rules
          #!/usr/bin/make -f
          %:
          	dh \$@
          EOF
          chmod +x debian/rules

      - name: Create changelog
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "0.1.0")
          dch --create -v ${VERSION}-dev$(date +%Y%m%d%H%M%S) --package bdcas --distribution unstable "Release"

      - name: Build package
        run: dpkg-buildpackage -us -uc -b

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bdcas_*.deb  # Modifica il percorso del pacchetto `.deb`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
