name: Update Wiki

permissions:
  contents: write 
  
on:
  push:
    branches:
      - main  

jobs:
  update_wiki:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3 

      - name: Checkout wiki repository
        uses: actions/checkout@v3 
        with:
          repository: Dksengine/bdcas.wiki  
          path: wiki  

      - name: Create assets directory (if not exists)
        run: |
          mkdir -p wiki/assets
      - name: Create Doc directory (if not exists)    
        run: |
          mkdir -p wiki/doc 

      - name: Copy documentation to wiki folder
        run: |
          cp README.md wiki/Home.md
          cp -r Doc/* wiki/doc/  
          cp assets/* wiki/assets/

      - name: Commit and push updated wiki
        run: |
          cd wiki 
          git config user.name "Dksengine"  
          git config user.email "info@dksengine.it" 
          git add .  
          git commit -m "Update Wiki Doc" --no-verify  
          git push  
