name: Update Wiki

permissions:
  contents: write  # Permessi necessari per fare il push nel repository Wiki
  
on:
  push:
    branches:
      - main  # Trigger sull'aggiornamento del branch main

jobs:
  update_wiki:
    runs-on: ubuntu-latest  # Esegui il job su Ubuntu

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3  # Checkout del repository principale

      - name: Checkout wiki repository
        uses: actions/checkout@v3  # Checkout del repository Wiki
        with:
          repository: Dksengine/bdcas.wiki  # Indica il repository della Wiki
          token: ${{ secrets.GITHUB_TOKEN }}  # Utilizza il token GitHub per l'accesso
          path: wiki  # Usa una cartella temporanea chiamata wiki per il checkout della Wiki

      - name: Create assets directory (if not exists)
        run: |
          mkdir -p wiki/assets  # Crea la cartella assets nella Wiki se non esiste già

      - name: Copy documentation to wiki folder
        run: |
          cp README.md wiki/Home.md  # Copia il README come Home nella Wiki
          cp -r Doc/* wiki/Doc/  # Copia la cartella Doc
          cp Doc/logo.png wiki/assets/  # Copia l'immagine/logo nella cartella assets

      - name: Commit and push updated wiki
        run: |
          cd wiki  # Entra nella cartella della Wiki
          git config user.name "Dksengine"  # Configura il nome utente
          git config user.email "info@dksengine.it"  # Configura l'email
          git add .  # Aggiungi tutte le modifiche
          git commit -m "Update Wiki Doc" --no-verify  # Commit con un messaggio
          git push  # Fai il push delle modifiche nella Wiki
